simulation:
  enable_viewer: true
  duration: 30.0
  dt: 0.01
  model_path: mujoco_menagerie/franka_fr3/fr3.xml
  opensim_path: OpenSIM_utils/Arm26/arm26.osim
  opensim_scale: -1.0
  controller: "AC"
  x_goal: [0.5, 0.5, 1.0, 1.57, 0.0, 0.0] 
  max_force: 50.0  # maximum possible voluntary contraction in Newtons

gui:
  window:
    title: Force Control GUI
    size: [800, 600]
    pos : [100, 100]
    color: [0.1, 0.1, 0.1]
  sliders:
    target_mvc:
      label: "%MVC (Target Effort)"
      range: [0.0, 100.0]
      default: 50.0
      controller: "all"
    max_force:
      label: "Max Force (N)"
      range: [0.0, 400.0]
      default: 50.0  # maximum possible voluntary contraction in Newtons
      controller: "all"
    M:
      label: "Mass M"
      range: [0.1, 100.0]
      default: 1.0
      controller: "AC"
    B:
      label: "Damping B"
      range: [0.0, 100.0]
      default: 10.0
      controller: "AC"
    K:
      label: "Stiffness K"
      range: [0.0, 100.0]
      default: 10.0
      controller: "AC"

admittance_controller:
  M    :   1.00
  B    :  10.00
  K    :  10.00
  Kp   : 100.00
  Kd   :  10.00
  M_min:   0.01
  M_max: 100.00
  B_min:   0.01
  B_max: 100.00
  K_min:   0.00
  K_max: 100.00

parallel_controller:
  Kp: 250.0
  Kd:   5.0
  force: [0.0, 0.0, -5.0]
