simulation:
  enable_viewer: true
  duration: 60.0
  dt: 0.01
  model_path: mujoco_menagerie/franka_fr3/fr3.xml
  controller: "AC"
  x_goal_offset: [0.5, 0.0, -1.0]  # relative offset from current pose

gui:
  init_force: [0.0, 0.0, -5.0]
  window:
    title: Force Control GUI
    size: [800, 600]
    pos : [100, 100]
    color: [0.1, 0.1, 0.1]
  sliders:
    target_mvc:
      label: "%MVC (Target Effort)"
      range: [0.0, 100.0]
      default: 60.0
      controller: "all"
    max_force:
      label: "Max Force (N)"
      range: [0.0, 500.0]
      default: 400.0  # maximum possible voluntary contraction in Newtons
      controller: "all"
    M:
      label: "Mass M"
      range: [0.1, 10.0]
      default: 1.0
      controller: "AC"
    B:
      label: "Damping B"
      range: [0.0, 200.0]
      default: 50.0
      controller: "AC"
    K:
      label: "Stiffness K"
      range: [0.0, 100.0]
      default: 0.0
      controller: "AC"

admittance_controller:
  M    :   1.00
  B    :  50.00
  K    :   0.00
  Kp   : 100.00
  Kd   :   0.00
  M_min:   0.01
  M_max: 100.00
  B_min:   0.01
  B_max: 100.00
  K_min:   0.00
  K_max: 100.00

parallel_controller:
  Kp: 250.0
  Kd:   5.0
  force: [0.0, 0.0, -5.0]
