simulation:
  duration: 60.0
  dt: 0.01
  model_path: mujoco_menagerie/franka_fr3/fr3.xml
  use_admittance: true
  x_goal: [0.5, 0.5, 1.0, 1.57, 0.0, 0.0] 
  max_force: 50.0  # maximum possible voluntary contraction in Newtons

admittance_controller:
  M: 1.0
  B: 10.0
  K: 10.0
  Kp: 100.0
  Kd: 10.0
