simulation:
  model_path: "franka_fr3/fr3.xml"      # Adjust path to your MuJoCo model
  site_name: "attachment_site"              
  initial_qpos: [2.09, -1.19, -2.4, -2.22, 1.39, 0.687, -1.08]  # This is a decent starting position from trial and error
  #dt: 0.002
  #duration: 10.0

admittance_controller:
  M: [10, 10, 10, 0.1, 0.1, 0.1]
  B: [30, 30, 30, 1, 1, 1]
  K: [200, 200, 200, 10, 10, 10]
  Kp: 200.0
  Kd: 10.0

forces:
  #external_force: [1, 0, 1, 0, 0, 0]
  desired_activation: 0.8 # the desired activation is what we want in our MUSCLES - and is achieved by some displacement of the EE which has a virtual stiffness 
  # we can achieve a desired activation by representing it as an external force - the force on the robot arm and the human arm are the same - but opposite directions

trajectory:
  type: "quarter_circle" 
  center: [0.4, 0.0, 0.4] # I tuned this to be appropriate
  radius: 0.289189 # Euclidian norm of (0.011649, -0.280635, 0.068841), meters
  frequency: 0.1
  